version: '3.8'
name: transit-api
services:
  transit-db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=transit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local